# Stage 1: Build the Go binary
FROM golang:1.20 AS builder

WORKDIR /app

COPY . .

RUN go build -o app

# Stage 2: Create a minimal runtime image
FROM scratch

WORKDIR /app

COPY --from=builder /app/app .

CMD ["./app"]